import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          <Link href="/shows/rewriteme">Rewrite URL</Link>
        </p>
        <p>
          <Link href="/shows/rewrite-absolute">Rewrite to absolute URL</Link>
        </p>
        <p>
          <Link href="/shows/rewrite-external">Rewrite to external URL</Link>
        </p>
        <p>
          <Link href="/shows/redirectme">Redirect URL</Link>
        </p>
        <p>
          <Link href="/shows/redirectexternal">Redirect to external URL</Link>
        </p>
        <p>
          <Link href="/shows/static/3">Add header to static page</Link>
        </p>
        <p>
          <Link href="/cookies" prefetch={false}>
            Cookie API
          </Link>
        </p>
        <p>
          <Link href="/api/hello">Adds `x-hello` request header</Link>
        </p>
        <p>
          <Link href="/static">Rewrite static page content</Link>
        </p>
        <p>
          <Link href="/headers">Adds `x-hello` request header to a rewrite</Link>
        </p>
        <p>
          <Link href="/previewTest">Preview mode</Link>
        </p>
      </main>
    </div>
  )
}
