import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'

export default function Home() {
  const { locale } = useRouter()
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>The current locale is {locale}</p>

        <div className={styles.grid}>
          <Link href="/dynamic/dynamic-1" className={styles.card}>
            <h2>Dynamic Page</h2>
          </Link>
          <Link href="/fallback/dynamic-2" className={styles.card}>
            <h2>Fallback Page</h2>
          </Link>
          <Link href="/redirectme" className={styles.card}>
            <h2>Redirect me</h2>
          </Link>
        </div>
      </main>
    </div>
  )
}
