[build]
command = "npm run build"
# publish = "dist/apps/demo-monorepo/.next"
# ignore = "if [ $CACHED_COMMIT_REF == $COMMIT_REF ]; then (exit 1); else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../..; fi;"

# [dev]
# command = "npm run start"
# targetPort = 4200

[[plugins]]
package = "./local-plugin"

[[plugins]]
package = "@netlify/plugin-local-install-core"
