[build]
command = "npm run build"
# If we wanted to publish `docs` as well as `web`, we'd need to have netlify.toml
# files in each project folder.
# See https://docs.netlify.com/configure-builds/monorepos/#build-multiple-sites-from-a-monorepo
publish = "apps/web/.next"

[[plugins]]
package = "./packages/local-plugin"

[[plugins]]
package = "@netlify/plugin-local-install-core"
