[build]
command = "next build && next export"
publish = "out"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../../"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"
NODE_VERSION = "17"

[dev]
framework = "#static"

[[plugins]]
package = "../../plugin"
