[build]
command = "next build && next export"
publish = "out"
ignore = "if [ $CACHED_COMMIT_REF == $COMMIT_REF ]; then (exit 1); else git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../..; fi;"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"
NODE_VERSION = "17"

[dev]
framework = "#static"

[[plugins]]
package = "../plugin-wrapper/"

[[plugins]]
package = "@netlify/plugin-local-install-core"
