name: Next Runtime Integration Tests

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Installing with LTS Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
      - name: NPM Install
        run: npm install
      - name: Run integration tests
        run: npm run test:integration
