name: Next Runtime Integration Tests

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  NEXT_SPLIT_API_ROUTES: true

jobs:
  build:
    name: Integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Installing with LTS Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Install netlify-cli and npm
        run: npm install -g netlify-cli@17.9.0 npm
      - name: NPM Install
        run: npm install
      - name: Run integration tests
        run: npm run test:integration
